---
dependencies:
  - role: download
    file: "{{ downloads.hyperkube }}"
  - role: download
    file: "{{ downloads.pod_infra }}"
  - role: kubernetes/secrets
  - role: download
    file: "{{ downloads.nginx }}"
    when: is_kube_master == false and loadbalancer_apiserver_localhost|default(false)
  - role: download
    file: "{{ downloads.testbox }}"
  - role: download
    file: "{{ downloads.kubednsmasq }}"
    when: not skip_dnsmasq_k8s|default(false)
  - role: download
    file: "{{ downloads.kubedns }}"
    when: not skip_dnsmasq_k8s|default(false)
